### PR TITLE
iio_utils.h: fix compilation

### LINKED ISSUE #39: Kernel 4.0 / Debian: make programs fails with "Undefined reference to `build_channel_array'"
According to README, since I am running newer kernel than 3.16 I should only type `make programs`? 
When doing so, I am getting linking error:

```bash
$ make programs
cd sensors && make all
make[1]: Entering directory '/home/me/yoga-laptop/sensors'
cc generic_buffer.c  -o generic_buffer
/tmp/ccpVnbqv.o: dans la fonction « main »:
generic_buffer.c:(.text+0x139a): référence indéfinie vers « build_channel_array »
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'generic_buffer' failed
make[1]: *** [generic_buffer] Error 1
make[1]: Leaving directory '/home/me/yoga-laptop/sensors'
Makefile:9: recipe for target 'programs' failed
make: *** [programs] Error 2
```

### PR DESCRIPTION
**Pull request by bagage**
Fixes #39 , see [this](http://stackoverflow.com/questions/6312597/is-inline-without-static-or-extern-ever-useful-in-c99) for reference about `inline`/`static inline`/`extern inline`.

### CODE REVIEW

**Comment by pfps** [comment]
The inclusion of iio_utils.h is a hack to permit easy compilation.  The file itself comes from the Linux IIO subsystem.   The better fix would be to see if the current version of the file works with light and orientation and request an update to this file.  An even better fix would be to figure out how to get these programs to compile in various distributions of Linus, which may require using config somehow.

**Comment by bagage** [comment]
OK, so it should be left unmodified. I'll change my PR accordingly then, thanks!

**Comment by bagage** [comment]
Modified - is it OK for you now?

**Comment by pfps** [comment]
I'll take a look, but it may be a while.

peter

**Comment by pfps** [comment]
OK, let's give it a try.

**Pull request merged**
